# Generated by Django 5.1.15 on 2026-08-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presence',
            field=models.CharField(choices=[('ACTIVE', '활동 중'), ('AWAY', '자리 비움')], db_default='ACTIVE', default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='presence_at',
            field=models.DateTimeField(blank=True, help_text='마지막으로 상태를 바꾼 시각', null=True),
        ),
    ]
