# Generated by Django 5.1.15 on 2026-08-13 05:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("meetings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="agent_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("mention_feasibility", models.BooleanField(default=True)),
                ("allow_schedule_change", models.BooleanField(default=True)),
                ("allow_midmeeting_question", models.BooleanField(default=False)),
                ("disclose_work_plan_thought", models.BooleanField(default=True)),
                ("active_version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "agent_settings",
            },
        ),
        migrations.CreateModel(
            name="AgentConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="새 대화", max_length=200)),
                (
                    "title_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="사용자가 직접 고치면 자동 갱신을 멈춥니다.",
                    ),
                ),
                (
                    "last_message_preview",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_conversation",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_prompt",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "접수"),
                            ("ANALYZING", "분석"),
                            ("SEARCHING", "검색"),
                            ("CHECKING_POLICY", "정책 확인"),
                            ("GENERATING", "생성"),
                            ("QUEUED_FOR_DELIVERY", "발송 대기"),
                            ("COMPLETED", "완료"),
                            ("FAILED", "실패"),
                        ],
                        default="RECEIVED",
                        max_length=24,
                    ),
                ),
                ("trace_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("hop_count", models.PositiveSmallIntegerField(default=0)),
                ("max_hops", models.PositiveSmallIntegerField(default=3)),
                ("settings_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "steps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="ReAct 단계. 실행 중에만 늘고 완료 후 불변입니다.",
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="검색 근거. 문서 제목은 스냅샷으로 남깁니다.",
                    ),
                ),
                ("result", models.TextField(blank=True, default="")),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_run",
            },
        ),
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("USER", "사용자"), ("AGENT", "대리인")], max_length=6
                    ),
                ),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agent.agentconversation",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="agent.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "agent_message",
            },
        ),
        migrations.CreateModel(
            name="AgentSettingsVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_settings_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_settings_version",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="PendingQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asker_name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("chat_room_id", models.UUIDField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("answer_body", models.TextField(blank=True, default="")),
                (
                    "asker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asked_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_questions",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agent.agentrun",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pending_question",
            },
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["meeting", "-created_at"], name="agent_run_meeting_1aa5d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentmessage",
            index=models.Index(
                fields=["conversation", "-sent_at"],
                name="agent_messa_convers_f29ec8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentsettingsversion",
            constraint=models.UniqueConstraint(
                fields=("user", "version"), name="uq_agent_settings_version"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingquestion",
            index=models.Index(
                fields=["target_user", "answered_at"],
                name="pending_que_target__a53298_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingquestion",
            index=models.Index(
                fields=["meeting"], name="pending_que_meeting_2f0cfa_idx"
            ),
        ),
    ]
