# Generated by Django 5.1.15 on 2026-08-15 05:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('MESSAGE', '회의 발언'), ('ANNOUNCEMENT', '일정 공지'), ('DM', '개인 알림')], max_length=16)),
                ('channel_id', models.CharField(blank=True, default='', max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('SENT', '발송됨'), ('FAILED', '실패 (재시도 대기)'), ('DEAD', '포기 (사람 확인 필요)')], db_index=True, default='PENDING', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox_events', to='agent.agentrun')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='orgs.team')),
            ],
            options={
                'db_table': 'outbox_event',
                'indexes': [models.Index(fields=['status', 'available_at'], name='outbox_even_status_426fab_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'idempotency_key'), name='uniq_outbox_team_idem')],
            },
        ),
    ]
