# Generated by Django 5.1.15 on 2026-08-16 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_outboxevent'),
        ('meetings', '0003_aibriefing_location_chips_briefingconfirmation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pendingquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('run', None), _negated=True), fields=('run',), name='uq_pending_question_run'),
        ),
    ]
