# Generated by Django 5.1.15 on 2026-08-16 17:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_pending_question_unique_run'),
        ('meetings', '0004_flow_work_mode'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(help_text='모바일 반응형 작업 진행 현황', max_length=200)),
                ('reason', models.TextField(help_text='왜 물었는가')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='', help_text='확인된 내용. 유보하면 빕니다.')),
                ('source', models.CharField(blank=True, choices=[('GITHUB', 'Github'), ('FIGMA', 'Figma'), ('NOTION', 'Notion')], default='', max_length=10)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asker', models.ForeignKey(help_text='조회한 대리인의 주인', on_delete=django.db.models.deletion.CASCADE, related_name='lookups_made', to=settings.AUTH_USER_MODEL)),
                ('edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookups', to='meetings.flowedge')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_lookups', to='orgs.project')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookups', to='agent.agentrun')),
                ('target', models.ForeignKey(help_text='조회받은 대리인의 주인', on_delete=django.db.models.deletion.CASCADE, related_name='lookups_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_lookup',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['project', '-occurred_at'], name='agent_looku_project_ba63cb_idx'), models.Index(fields=['target', '-occurred_at'], name='agent_looku_target__dc0c14_idx')],
            },
        ),
    ]
