# Generated by Django 5.1.15 on 2026-08-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_agent_lookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='tone',
            field=models.CharField(choices=[('FORMAL', '정중하게'), ('FRIENDLY', '친근하게'), ('CONCISE', '간결하게')], default='FORMAL', max_length=10),
        ),
    ]
