# Generated by Django 5.1.15 on 2026-08-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agentsettings_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='agent_name',
            field=models.CharField(blank=True, default='', help_text='대리인 호칭. 비면 `{사용자 이름}의 Bordo` 를 씁니다.', max_length=40),
        ),
    ]
