# Generated by Django 5.1.15 on 2026-08-15 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guild_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_links', to='orgs.team')),
            ],
            options={
                'db_table': 'discord_guild_link',
            },
        ),
        migrations.CreateModel(
            name='LinkCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('discord_user_id', models.CharField(db_index=True, max_length=40)),
                ('guild_id', models.CharField(blank=True, default='', max_length=40)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discord_link_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discord_link_code',
                'indexes': [models.Index(fields=['discord_user_id', 'used_at'], name='discord_lin_discord_075bba_idx')],
            },
        ),
    ]
