# Generated by Django 5.1.15 on 2026-08-13 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('visibility', models.CharField(choices=[('team', '팀 공개'), ('private', '비공개')], default='team', max_length=10)),
                ('content', models.TextField(blank=True, default='', help_text='원문 마크다운')),
                ('summary', models.TextField(blank=True, default='', help_text='검색 결과 미리보기. 서버가 채웁니다.')),
                ('sections', models.JSONField(blank=True, default=list, help_text='[{heading, one_line_summary, body}]')),
                ('delivery_context', models.JSONField(blank=True, default=list, help_text='`문서 전달 맥락`. 이 문서가 오가게 된 대화 근거.')),
                ('direction_label', models.CharField(blank=True, default='', max_length=200)),
                ('hash', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('masked_secrets', models.PositiveSmallIntegerField(default=0)),
                ('indexed', models.BooleanField(default=False, help_text='임베딩 색인 완료 여부. 2차에서 채웁니다.')),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orgs.project')),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('sections', models.JSONField(blank=True, default=list)),
                ('hash', models.CharField(blank=True, default='', max_length=80)),
                ('source', models.CharField(choices=[('web_edit', '웹 편집'), ('mcp_push', 'MCP 업로드'), ('restore', '버전 복원')], default='web_edit', max_length=10)),
                ('restored_from', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'db_table': 'document_version',
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'category'], name='document_project_0ebd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'visibility'], name='document_project_9778f1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner'], name='document_owner_i_c24308_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uq_document_version'),
        ),
    ]
