# Generated by Django 5.1.15 on 2026-08-13 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('MEETING', '회의'), ('DEADLINE', '마감'), ('BLOCK', '일정 블록')], default='MEETING', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', '초안'), ('SCHEDULED', '예정'), ('CONFIRMED', '확정'), ('CANCELLED', '취소됨')], default='SCHEDULED', max_length=10)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('discord_notified', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='orgs.project')),
                ('related_meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_event', to='meetings.meeting')),
            ],
            options={
                'db_table': 'calendar_event',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='calendars.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_event_participant',
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('agent_utterance', '대리인 발언'), ('meeting_announcement', '회의 공지'), ('meeting_reminder', '회의 리마인더'), ('pending_question', '정보 질문'), ('meeting_report', '회의 보고서'), ('schedule_changed', '일정 변경')], max_length=24)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('CLAIMED', '가져감'), ('SENT', '전송됨'), ('ACKED', '확인됨'), ('RETRY_WAIT', '재시도 대기'), ('DEAD', '실패 확정')], default='PENDING', max_length=12)),
                ('target', models.JSONField(blank=True, default=dict, help_text='{"kind":"channel","channel_id":"..."}')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=60)),
                ('error_message', models.TextField(blank=True, default='')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('discord_message_id', models.CharField(blank=True, default='', max_length=40)),
                ('source_type', models.CharField(blank=True, default='', max_length=30)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='orgs.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='orgs.team')),
            ],
            options={
                'db_table': 'outbox_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('T_MINUS_1D', '하루 전'), ('T_MINUS_15M', '15분 전')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='calendars.calendarevent')),
            ],
            options={
                'db_table': 'calendar_reminder',
            },
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['project', 'start_at'], name='calendar_ev_project_881779_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['project', 'status'], name='calendar_ev_project_55c12b_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='uq_event_participant'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['status', 'next_retry_at'], name='outbox_even_status_c6df86_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['source_type', 'source_id'], name='outbox_even_source__6bed80_idx'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.UniqueConstraint(fields=('team', 'idempotency_key'), name='uq_outbox_idempotency'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['scheduled_at', 'cancelled_at'], name='calendar_re_schedul_d9128f_idx'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(fields=('event', 'notification_type'), name='uq_reminder_idempotency'),
        ),
    ]
