# Generated by Django 5.1.15 on 2026-08-13 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(help_text='work.updated 등', max_length=40)),
                ('target_id', models.UUIDField()),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='orgs.project')),
            ],
            options={
                'db_table': 'activity_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['project', '-occurred_at'], name='activity_ev_project_03ea55_idx'), models.Index(fields=['target_id'], name='activity_ev_target__510a8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('visibility', models.CharField(choices=[('team', '팀 공개'), ('private', '비공개')], default='team', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P2', max_length=2)),
                ('planned_start_at', models.DateTimeField(blank=True, null=True)),
                ('planned_end_at', models.DateTimeField(blank=True, null=True)),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='선행 plan_item id 배열. 순환은 막습니다.')),
                ('status', models.CharField(choices=[('TODO', '예정'), ('IN_PROGRESS', '진행 중'), ('BLOCKED', '막힘'), ('DONE', '완료')], default='TODO', max_length=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='orgs.project')),
            ],
            options={
                'db_table': 'plan_item',
                'ordering': ['priority', 'planned_end_at'],
                'indexes': [models.Index(fields=['project', 'owner'], name='plan_item_project_092801_idx'), models.Index(fields=['project', 'priority'], name='plan_item_project_85a82e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThoughtItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('visibility', models.CharField(choices=[('team', '팀 공개'), ('private', '비공개')], default='team', max_length=10)),
                ('topic', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('confidence', models.FloatField(default=0.5)),
                ('requires_discussion', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', '미해결'), ('RESOLVED', '해결됨'), ('PROMOTED', '안건으로 승격')], default='OPEN', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='orgs.project')),
                ('promoted_from_question', models.ForeignKey(blank=True, help_text='정보 질문에 답하며 `promote_to_thought` 로 승격된 경우', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_thoughts', to='agent.pendingquestion')),
            ],
            options={
                'db_table': 'thought_item',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'owner'], name='thought_ite_project_f34c24_idx'), models.Index(fields=['project', 'requires_discussion'], name='thought_ite_project_ad0822_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('visibility', models.CharField(choices=[('team', '팀 공개'), ('private', '비공개')], default='team', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('TODO', '예정'), ('IN_PROGRESS', '진행 중'), ('BLOCKED', '막힘'), ('DONE', '완료')], default='IN_PROGRESS', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('blockers', models.JSONField(blank=True, default=list, help_text='막힌 이유. `왜 안 되고 있나` 의 답입니다.')),
                ('expected_end_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='orgs.project')),
            ],
            options={
                'db_table': 'work_item',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['project', 'owner'], name='work_item_project_61edc8_idx'), models.Index(fields=['project', 'status'], name='work_item_project_635511_idx')],
            },
        ),
    ]
