# Generated by Django 5.1.15 on 2026-08-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitem',
            name='source',
            field=models.CharField(choices=[('web', '웹'), ('mcp', '개인 AI'), ('agent', '대리인')], default='web', max_length=8),
        ),
        migrations.AddField(
            model_name='thoughtitem',
            name='source',
            field=models.CharField(choices=[('web', '웹'), ('mcp', '개인 AI'), ('agent', '대리인')], default='web', max_length=8),
        ),
        migrations.AddField(
            model_name='workitem',
            name='source',
            field=models.CharField(choices=[('web', '웹'), ('mcp', '개인 AI'), ('agent', '대리인')], default='web', max_length=8),
        ),
    ]
