# Generated by Django 5.1.15 on 2026-08-13 05:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("project_name", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "초안"),
                            ("SCHEDULED", "예정"),
                            ("CONFIRMED", "확정"),
                            ("ACTIVE", "진행 중"),
                            ("PROCESSING_REPORT", "보고서 생성 중"),
                            ("ENDED", "종료"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("duration_min", models.PositiveSmallIntegerField(default=60)),
                (
                    "discord_channel_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="회의가 실제로 열리는 곳",
                        max_length=40,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="화살표 opacity 계산의 기준 시각",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="orgs.project",
                    ),
                ),
            ],
            options={
                "db_table": "meeting",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("category", models.CharField(blank=True, default="", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("DISCUSSED", "논의됨"),
                            ("DEFERRED", "보류"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                (
                    "direction_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="`AI 대리인 → A, B` 처럼 서버가 조립해 둡니다.",
                        max_length=200,
                    ),
                ),
                ("created_by_agent", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendas",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "agenda",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FlowFilterPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60)),
                ("participant_ids", models.JSONField(blank=True, default=list)),
                ("content_types", models.JSONField(blank=True, default=list)),
                ("surfaces", models.JSONField(blank=True, default=list)),
                ("since_minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_filter_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "flow_filter_preset",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingSummary",
            fields=[
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="summary",
                        serialize=False,
                        to="meetings.meeting",
                    ),
                ),
                ("discovered_issues", models.JSONField(blank=True, default=list)),
                ("changes", models.JSONField(blank=True, default=list)),
                ("next_plans", models.JSONField(blank=True, default=list)),
                ("one_line", models.CharField(blank=True, default="", max_length=300)),
                ("main_opinions", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "meeting_summary",
            },
        ),
        migrations.CreateModel(
            name="AiBriefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("narrative", models.TextField(blank=True, default="")),
                ("used_answers", models.JSONField(blank=True, default=list)),
                ("deferred_answers", models.JSONField(blank=True, default=list)),
                ("settings_version", models.PositiveIntegerField(default=1)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="briefings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="briefings",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "ai_briefing",
            },
        ),
        migrations.CreateModel(
            name="MeetingDocumentRef",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("team", "팀 공개"), ("private", "비공개")],
                        default="team",
                        max_length=10,
                    ),
                ),
                ("sections", models.JSONField(blank=True, default=list)),
                ("delivery_context", models.JSONField(blank=True, default=list)),
                (
                    "direction_label",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_refs",
                        to="orgs.project",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_document_ref",
            },
        ),
        migrations.CreateModel(
            name="FlowEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("WORK", "작업"), ("MEETING", "회의")], max_length=10
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "문서"),
                            ("PLAN", "계획"),
                            ("OPINION", "의견"),
                            ("REQUEST", "요청사항"),
                            ("REVISION", "수정사항"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        choices=[("SERVICE", "서비스"), ("DISCORD", "Discord")],
                        default="SERVICE",
                        max_length=10,
                    ),
                ),
                (
                    "from_node",
                    models.JSONField(help_text='{"id","kind","user_id","name"}'),
                ),
                (
                    "to_nodes",
                    models.JSONField(
                        default=list, help_text="같은 모양의 배열. 1:N 가능."
                    ),
                ),
                ("participant_ids", models.JSONField(blank=True, default=list)),
                ("label", models.CharField(max_length=60)),
                (
                    "direction_label",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "extra_participant_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("occurred_at", models.DateTimeField()),
                ("opacity", models.FloatField(default=1.0)),
                (
                    "agenda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flow_edges",
                        to="meetings.agenda",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow_edges",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meetings.meetingdocumentref",
                    ),
                ),
            ],
            options={
                "db_table": "flow_edge",
                "ordering": ["occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_name", models.CharField(max_length=100)),
                (
                    "attendance",
                    models.CharField(
                        choices=[
                            ("PENDING", "미정"),
                            ("PRESENT", "참석"),
                            ("ABSENT", "불참"),
                            ("DELEGATED", "대리 참석"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "delegated",
                    models.BooleanField(
                        default=False, help_text="대리 참석 활성화 여부"
                    ),
                ),
                (
                    "delegate_prompt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="이 회의에 한정된 지시. 비면 기본 프롬프트를 씁니다.",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meeting_participant",
            },
        ),
        migrations.CreateModel(
            name="Utterance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("participant_name", models.CharField(max_length=100)),
                ("body", models.TextField()),
                ("spoken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utterances",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "utterance",
                "ordering": ["spoken_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["project", "-scheduled_at"], name="meeting_project_9fe92a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["-scheduled_at"], name="meeting_schedul_599c04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aibriefing",
            index=models.Index(
                fields=["user", "read_at"], name="ai_briefing_user_id_d360fa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="aibriefing",
            constraint=models.UniqueConstraint(
                fields=("meeting", "user"), name="uq_ai_briefing"
            ),
        ),
        migrations.AddIndex(
            model_name="agenda",
            index=models.Index(
                fields=["meeting", "sort_order"], name="agenda_meeting_72b3f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowedge",
            index=models.Index(
                fields=["meeting", "occurred_at"], name="flow_edge_meeting_0b3fde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flowedge",
            index=models.Index(
                fields=["meeting", "category", "content_type"],
                name="flow_edge_meeting_bdcf7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingparticipant",
            index=models.Index(
                fields=["user", "attendance"], name="meeting_par_user_id_c8751f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingparticipant",
            constraint=models.UniqueConstraint(
                fields=("meeting", "user"), name="uq_meeting_participant"
            ),
        ),
        migrations.AddIndex(
            model_name="utterance",
            index=models.Index(
                fields=["meeting", "spoken_at"], name="utterance_meeting_f8f6dd_idx"
            ),
        ),
    ]
