# Generated by Django 5.1.15 on 2026-08-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowedge',
            name='content_type',
            field=models.CharField(choices=[('DOCUMENT', '문서'), ('PLAN', '계획'), ('OPINION', '의견'), ('REQUEST', '요청사항'), ('CHANGE', '변동사항'), ('SCHEDULE', '일정'), ('CONCLUSION', '결론'), ('ETC', '기타')], max_length=10),
        ),
    ]
