# Generated by Django 5.1.15 on 2026-08-14 05:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowedge',
            name='content_type',
            field=models.CharField(choices=[('DOCUMENT', '문서'), ('PLAN', '계획'), ('OPINION', '의견'), ('REQUEST', '요청사항'), ('CHANGE', '변동사항'), ('SCHEDULE', '일정'), ('CONCLUSION', '결론'), ('ETC', '기타')], max_length=10),
        ),
        migrations.CreateModel(
            name='BriefingConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.agenda')),
                ('edge', models.ForeignKey(blank=True, help_text='`해당 내용 보기 →` 가 가리키는 화살표', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to='meetings.flowedge')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefing_confirmations', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefing_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'briefing_confirmation',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['meeting', 'user', 'confirmed_at'], name='briefing_co_meeting_b718fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='BriefingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, default='', help_text='기한이 없을 때 대신 붙는 문구', max_length=200)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_task_id', models.UUIDField(blank=True, help_text='받아들여 태스크가 된 경우 그 id', null=True)),
                ('edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='meetings.flowedge')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefing_requests', to='meetings.meeting')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_briefing_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='요청을 받은 사람', on_delete=django.db.models.deletion.CASCADE, related_name='briefing_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'briefing_request',
                'ordering': ['due_at', '-created_at'],
                'indexes': [models.Index(fields=['meeting', 'user'], name='briefing_re_meeting_8793c0_idx'), models.Index(fields=['user', 'accepted_task_id'], name='briefing_re_user_id_9f3797_idx')],
            },
        ),
    ]
