# Generated by Django 5.1.15 on 2026-08-15 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_flowedge_content_type'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aibriefing',
            name='location_chips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='BriefingConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_key', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('occurred_at', models.DateTimeField()),
                ('body', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.agenda')),
                ('edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.flowedge')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'briefing_confirmation',
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['user', 'confirmed_at'], name='briefing_co_user_id_8961e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'user', 'source_key'), name='uq_briefing_confirmation')],
            },
        ),
        migrations.CreateModel(
            name='BriefingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_key', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('occurred_at', models.DateTimeField()),
                ('requester_name', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.flowedge')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='meetings.meeting')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefing_requests', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'briefing_request',
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['user', 'accepted_at'], name='briefing_re_user_id_b288bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'user', 'source_key'), name='uq_briefing_request')],
            },
        ),
    ]
