# Generated by Django 5.1.15 on 2026-08-16 16:44

import django.db.models.deletion
from django.db import migrations, models


def fill_project_from_meeting(apps, schema_editor):
    """
    기존 엣지의 `project` 를 회의에서 가져와 채웁니다.

    지금까지 모든 엣지에는 회의가 있었으므로 빠짐없이 채워집니다. 이 단계가
    없으면 다음 `AlterField`(null=False)가 기존 행 때문에 죽어 배포가 멈춥니다.
    """
    FlowEdge = apps.get_model("meetings", "FlowEdge")
    for edge in FlowEdge.objects.filter(project__isnull=True).select_related("meeting"):
        if edge.meeting_id:
            FlowEdge.objects.filter(pk=edge.pk).update(project_id=edge.meeting.project_id)


def drop_orphans(apps, schema_editor):
    """
    회의도 프로젝트도 없는 엣지는 그릴 자리가 없습니다.

    정상 경로에서는 생기지 않지만, 남아 있으면 `AlterField` 가 죽습니다.
    """
    FlowEdge = apps.get_model("meetings", "FlowEdge")
    FlowEdge.objects.filter(project__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_aibriefing_location_chips_briefingconfirmation_and_more'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowedge',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_edges', to='orgs.project'),
        ),
        migrations.AddField(
            model_name='flowedge',
            name='source',
            field=models.CharField(blank=True, choices=[('GITHUB', 'Github'), ('FIGMA', 'Figma'), ('NOTION', 'Notion')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='flowedge',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='flowedge',
            name='content_type',
            field=models.CharField(choices=[('DOCUMENT', '문서'), ('PLAN', '계획'), ('OPINION', '의견'), ('REQUEST', '요청사항'), ('CHANGE', '변동사항'), ('SCHEDULE', '일정'), ('CONCLUSION', '결론'), ('ETC', '기타'), ('WORK', '작업'), ('REVISION', '수정'), ('FEEDBACK', '피드백'), ('SHARE', '공유'), ('AI_LOOKUP', 'AI 조회')], max_length=10),
        ),
        migrations.AlterField(
            model_name='flowedge',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_edges', to='meetings.meeting'),
        ),
        # 인덱스를 붙이기 전에 값을 채웁니다. 순서가 바뀌면 아래 AlterField 가
        # 기존 행 때문에 IntegrityError 로 죽어 배포 전체가 멈춥니다.
        migrations.RunPython(fill_project_from_meeting, migrations.RunPython.noop),
        migrations.RunPython(drop_orphans, migrations.RunPython.noop),
        # 값이 다 찼으니 이제 필수로 조입니다.
        migrations.AlterField(
            model_name='flowedge',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_edges', to='orgs.project'),
        ),
        migrations.AddIndex(
            model_name='flowedge',
            index=models.Index(fields=['project', 'category', 'occurred_at'], name='flow_edge_project_f9c60d_idx'),
        ),
    ]
