# Generated by Django 5.1.15 on 2026-08-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_flow_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='delegate_sources',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
