# Generated by Django 5.1.15 on 2026-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_flow_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='allowed_sources',
            field=models.JSONField(blank=True, default=None, help_text='이 회의에서 대리인이 근거로 쓸 자료 종류. null 이면 고른 적 없음(제한 없음), [] 면 아무것도 쓰지 않음.', null=True),
        ),
    ]
