# Generated by Django 5.1.15 on 2026-08-18 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('meetings', '0005_meetingparticipant_allowed_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowedge',
            name='work_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_edges', to='documents.document'),
        ),
    ]
