# Generated by Django 5.1.15 on 2026-08-18 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_flowedge_work_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebatePoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_key', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(help_text='질문형. `A 할 것인가, B 할 것인가?`', max_length=200)),
                ('options', models.JSONField(blank=True, default=list)),
                ('rationale', models.TextField(blank=True, default='', help_text='`Bordo가 이렇게 예측했어요` 문단')),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('created_by_agent', models.BooleanField(default=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_points', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meeting_debate_point',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebateStance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_key', models.CharField(blank=True, default='', help_text='고른 선택지. 비어 있을 수 있습니다.', max_length=8)),
                ('body', models.TextField()),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stances', to='meetings.debatepoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_stances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_debate_stance',
                'ordering': ['point__order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='debatepoint',
            index=models.Index(fields=['meeting', 'order'], name='meeting_deb_meeting_b7105b_idx'),
        ),
        migrations.AddConstraint(
            model_name='debatepoint',
            constraint=models.UniqueConstraint(fields=('meeting', 'source_key'), name='uq_debate_point'),
        ),
        migrations.AddIndex(
            model_name='debatestance',
            index=models.Index(fields=['user'], name='meeting_deb_user_id_18e1a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='debatestance',
            constraint=models.UniqueConstraint(fields=('point', 'user'), name='uq_debate_stance'),
        ),
    ]
