# Generated by Django 5.1.15 on 2026-08-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_debate_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='prompt_override',
            field=models.JSONField(blank=True, default=None, help_text='이 회의에만 쓸 시스템 프롬프트 목록. null 이면 평소 것 그대로, [] 면 아무 프롬프트도 쓰지 않음.', null=True),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='settings_override',
            field=models.JSONField(blank=True, default=dict, help_text='이 회의에만 적용할 설정. 바꾼 키만 담습니다. {} 면 평소 설정 그대로.'),
        ),
    ]
