# Generated by Django 5.1.15 on 2026-08-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_participant_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
    ]
