# Generated by Django 5.1.15 on 2026-08-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_plan_edges_to_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowedge',
            name='delivery_context',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
