# Generated by Django 5.1.15 on 2026-08-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_plan_edges_to_conclusion'),
        ('orgs', '0002_team_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSummary',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='work_summary', serialize=False, to='orgs.project')),
                ('discovered_issues', models.JSONField(blank=True, default=list)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('next_plans', models.JSONField(blank=True, default=list)),
                ('one_line', models.CharField(blank=True, default='', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'work_summary',
            },
        ),
    ]
