# Generated by Django 5.1.15 on 2026-08-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_flowedge_delivery_context'),
        ('meetings', '0011_worksummary'),
    ]

    operations = [
    ]
