# Generated by Django 5.1.15 on 2026-08-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
