# Generated by Django 5.1.15 on 2026-08-13 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('AI', '나의 AI 대리인'), ('DIRECT', '개인 채팅'), ('TEAM', '팀 채팅'), ('PROJECT', '프로젝트 채팅'), ('PEER_AGENT', '동료의 AI 대리인')], max_length=12)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('team_name', models.CharField(blank=True, default='', max_length=120)),
                ('project_name', models.CharField(blank=True, default='', max_length=120)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('agent_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peer_agent_rooms', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='orgs.project')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='orgs.team')),
            ],
            options={
                'db_table': 'chat_room',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name', models.CharField(max_length=100)),
                ('is_agent', models.BooleanField(default=False, help_text='대리인이 보낸 메시지')),
                ('body', models.TextField(blank=True, default='')),
                ('is_important', models.BooleanField(default=False)),
                ('client_message_id', models.CharField(blank=True, default='', help_text='`room_id + client_message_id` 로 중복 전송을 막습니다.', max_length=80)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pending_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_answers', to='agent.pendingquestion')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('UPLOADED', '업로드됨'), ('ATTACHED', '메시지에 붙음'), ('EXPIRED', '만료')], default='UPLOADED', max_length=10)),
                ('kind', models.CharField(choices=[('IMAGE', '이미지'), ('FILE', '파일')], default='FILE', max_length=6)),
                ('name', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_attachments', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_attachment',
            },
        ),
        migrations.CreateModel(
            name='DailyChatSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('one_line', models.CharField(blank=True, default='', max_length=300)),
                ('my_todos', models.JSONField(blank=True, default=list)),
                ('schedules', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_daily_summary',
            },
        ),
        migrations.CreateModel(
            name='MessageImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importance_receipts', to='chat.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importance_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_message_importance',
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('visible_from', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_room_member',
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['team', 'project'], name='chat_room_team_id_7a4652_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['-last_message_at'], name='chat_room_last_me_f57be7_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('type', 'dedupe_key'), name='uq_chat_room_dedupe'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'TEAM')), fields=('team',), name='uq_chat_room_team'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'PROJECT')), fields=('project',), name='uq_chat_room_project'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', '-sent_at'], name='chat_messag_room_id_48347a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'is_important'], name='chat_messag_room_id_7a2461_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id', ''), _negated=True), fields=('room', 'client_message_id'), name='uq_chat_message_client_id'),
        ),
        migrations.AddIndex(
            model_name='chatattachment',
            index=models.Index(fields=['room', 'status'], name='chat_attach_room_id_d01def_idx'),
        ),
        migrations.AddIndex(
            model_name='chatattachment',
            index=models.Index(fields=['status', 'expires_at'], name='chat_attach_status_dfea20_idx'),
        ),
        migrations.AddIndex(
            model_name='dailychatsummary',
            index=models.Index(fields=['room', '-date'], name='chat_daily__room_id_c4823e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailychatsummary',
            constraint=models.UniqueConstraint(fields=('room', 'date'), name='uq_chat_daily_summary'),
        ),
        migrations.AddIndex(
            model_name='messageimportance',
            index=models.Index(fields=['user', 'confirmed_at'], name='chat_messag_user_id_43c9aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='messageimportance',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='uq_message_importance'),
        ),
        migrations.AddIndex(
            model_name='roommember',
            index=models.Index(fields=['user', 'left_at'], name='chat_room_m_user_id_07a2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='roommember',
            index=models.Index(fields=['room', 'left_at'], name='chat_room_m_room_id_d48eb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='roommember',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='uq_chat_room_member'),
        ),
    ]
