# Generated by Django 5.1.15 on 2026-08-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='answered_while_away',
            field=models.BooleanField(default=False),
        ),
    ]
