# Generated by Django 5.1.15 on 2026-08-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatattachment',
            name='stored_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
