# Generated by Django 5.1.15 on 2026-08-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_answered_while_away'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='muted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
