# Generated by Django 5.1.15 on 2026-08-20 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatattachment_stored_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatattachment',
            name='client_upload_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='chatattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('client_upload_id__gt', '')), fields=('uploader', 'client_upload_id'), name='uq_chat_attachment_client_upload'),
        ),
    ]
